"use client";
import { useState } from "react";
import { MessageSquare, Reply, Trash2 } from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { formatDateTime } from "@/lib/utils";

type Post = { id:string; content:string; createdAt:string|Date; authorId:string; author:{name:string;role:string}; replies:Post[] };

export function DiscussionBoard({ courseId, posts, currentUserId, canModerate }: {courseId:string;posts:Post[];currentUserId:string;canModerate:boolean}) {
  const[content,setContent]=useState(""); const[loading,setLoading]=useState(false); const[replyTo,setReplyTo]=useState<string|null>(null);
  async function submit(parentId?:string|null){if(!content.trim())return;setLoading(true);const response=await fetch(`/api/courses/${courseId}/discussions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({content,parentId:parentId||null})});setLoading(false);if(response.ok){setContent("");setReplyTo(null);window.location.reload();}else{const result=await response.json();alert(result.error||"Could not post");}}
  async function remove(id:string){if(!confirm("Delete this discussion post?"))return;const response=await fetch(`/api/discussions/${id}`,{method:"DELETE"});if(response.ok)window.location.reload();else alert("Could not delete post");}
  function renderPost(post:Post, nested=false){return <div key={post.id} className={nested?"ml-6 border-l pl-4":"rounded-lg border bg-white p-4"}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="font-semibold">{post.author.name}</span><Badge variant={post.author.role==="LECTURER"?"success":"outline"}>{post.author.role}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{formatDateTime(post.createdAt)}</p></div>{canModerate||post.authorId===currentUserId?<Button size="icon" variant="ghost" onClick={()=>remove(post.id)} aria-label="Delete post"><Trash2 className="h-4 w-4 text-red-500" /></Button>:null}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{post.content}</p><Button size="sm" variant="ghost" className="mt-2" onClick={()=>{setReplyTo(post.id);setContent("");}}><Reply className="h-4 w-4" />Reply</Button>{replyTo===post.id?<div className="mt-3 space-y-2"><Textarea value={content} onChange={(e)=>setContent(e.target.value)} placeholder={`Reply to ${post.author.name}`} /><div className="flex gap-2"><Button size="sm" disabled={loading} onClick={()=>submit(post.id)}>Post reply</Button><Button size="sm" variant="ghost" onClick={()=>setReplyTo(null)}>Cancel</Button></div></div>:null}{post.replies?.length?<div className="mt-4 space-y-4">{post.replies.map((reply)=>renderPost(reply,true))}</div>:null}</div>}
  return <div><div className="rounded-lg border bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2"><MessageSquare className="h-5 w-5 text-primary" /><h3 className="font-semibold">Start a discussion</h3></div><Textarea value={replyTo?"":content} onChange={(e)=>setContent(e.target.value)} placeholder={canModerate?"Post an announcement or discussion prompt…":"Ask a question or share an idea…"} disabled={Boolean(replyTo)} /><Button className="mt-3" disabled={loading||Boolean(replyTo)} onClick={()=>submit(null)}>{loading?"Posting…":"Post message"}</Button></div><div className="mt-6 space-y-4">{posts.length?posts.map((post)=>renderPost(post)):<div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No discussion posts yet. Start the conversation.</div>}</div></div>;
}
