import Link from "next/link";
import { BookOpen, Edit3, Plus } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { DeleteCourseButton } from "@/components/forms/delete-course-button";

export default async function ManageCoursesPage(){const user=await requireUser(["LECTURER"]);const courses=await db.course.findMany({where:{lecturerId:user.id},include:{_count:{select:{enrollments:true,materials:true,assignments:true}}},orderBy:{createdAt:"desc"}});return <DashboardShell user={user}><div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="page-heading"><h1>Manage courses</h1><p>Create, publish, edit and organise your course content.</p></div><Link href="/lecturer/courses/new" className={buttonVariants()}><Plus className="h-4 w-4"/>New course</Link></div>{courses.length?<div className="grid gap-5 lg:grid-cols-2">{courses.map(course=><Card key={course.id} className="hover:-translate-y-0.5 hover:border-primary/25"><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><Badge>{course.category}</Badge><Badge variant={course.isPublished?"success":"warning"}>{course.isPublished?"Published":"Draft"}</Badge></div><h2 className="mt-3 text-xl font-black text-[#12201c]">{course.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{course.description}</p></div><span className="grid h-11 w-11 shrink-0 place-items-center rounded-lg bg-primary/10 text-primary"><BookOpen className="h-5 w-5"/></span></div><div className="mt-5 flex flex-wrap gap-2 text-xs font-bold text-muted-foreground"><span className="rounded-full bg-[#eef8f1] px-2.5 py-1">{course._count.enrollments} students</span><span className="rounded-full bg-[#eef8f1] px-2.5 py-1">{course._count.materials} materials</span><span className="rounded-full bg-[#eef8f1] px-2.5 py-1">{course._count.assignments} assignments</span></div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/lecturer/courses/${course.id}/manage`} className={buttonVariants({size:"sm"})}><Edit3 className="h-4 w-4"/>Manage</Link><Link href={`/courses/${course.id}`} className={buttonVariants({size:"sm",variant:"outline"})}>View</Link><DeleteCourseButton courseId={course.id}/></div></CardContent></Card>)}</div>:<div className="empty-premium"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-lg bg-[#eef8f1] text-primary"><BookOpen className="h-7 w-7"/></span><h2 className="mt-4 font-black text-[#12201c]">No courses yet</h2><p className="mt-2 text-sm text-muted-foreground">Create your first course to begin adding learning materials and assignments.</p></div></div>}</div></DashboardShell>}
