import Link from "next/link";
import { BookOpen, Edit3, Plus } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";
import { DeleteCourseButton } from "@/components/forms/delete-course-button";

export default async function ManageCoursesPage(){const user=await requireUser(["LECTURER"]);const courses=await db.course.findMany({where:{lecturerId:user.id},include:{_count:{select:{enrollments:true,materials:true,assignments:true}}},orderBy:{createdAt:"desc"}});return <DashboardShell user={user}><div className="space-y-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-3xl font-bold">Manage courses</h1><p className="mt-2 text-muted-foreground">Create, publish, edit and organise your course content.</p></div><Link href="/lecturer/courses/new" className={buttonVariants()}><Plus className="h-4 w-4"/>New course</Link></div>{courses.length?<div className="grid gap-5 lg:grid-cols-2">{courses.map(course=><Card key={course.id}><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><Badge>{course.category}</Badge><Badge variant={course.isPublished?"success":"warning"}>{course.isPublished?"Published":"Draft"}</Badge></div><h2 className="mt-3 text-xl font-semibold">{course.title}</h2><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{course.description}</p></div><BookOpen className="h-8 w-8 shrink-0 text-primary/40"/></div><div className="mt-5 flex flex-wrap gap-4 text-xs text-muted-foreground"><span>{course._count.enrollments} students</span><span>{course._count.materials} materials</span><span>{course._count.assignments} assignments</span></div><div className="mt-5 flex gap-2"><Link href={`/lecturer/courses/${course.id}/manage`} className={buttonVariants({size:"sm"})}><Edit3 className="h-4 w-4"/>Manage</Link><Link href={`/courses/${course.id}`} className={buttonVariants({size:"sm",variant:"outline"})}>View</Link><DeleteCourseButton courseId={course.id}/></div></CardContent></Card>)}</div>:<div className="rounded-lg border border-dashed p-12 text-center"><BookOpen className="mx-auto h-10 w-10 text-muted-foreground"/><h2 className="mt-4 font-semibold">No courses yet</h2><p className="mt-2 text-sm text-muted-foreground">Create your first course to begin adding learning materials and assignments.</p></div>}</div></DashboardShell>}
