import { notFound } from "next/navigation";
import { ArrowLeft, CalendarClock } from "lucide-react";
import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatDateTime } from "@/lib/utils";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { SubmissionForm } from "@/components/forms/submission-form";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default async function SubmitAssignmentPage({params}:{params:Promise<{id:string;assignmentId:string}>}){const{id,assignmentId}=await params;const user=await requireUser(["STUDENT"]);const assignment=await db.assignment.findFirst({where:{id:assignmentId,courseId:id,course:{enrollments:{some:{userId:user.id}}}},include:{course:{select:{title:true}},submissions:{where:{studentId:user.id}}}});if(!assignment)notFound();const existing=assignment.submissions[0]||null;return <DashboardShell user={user}><div className="mx-auto max-w-3xl"><Link href={`/courses/${id}`} className="inline-flex items-center gap-2 text-sm font-black text-primary"><ArrowLeft className="h-4 w-4"/>Back to course</Link><div className="page-heading mt-5"><p>{assignment.course.title}</p><h1>{assignment.title}</h1><div className="mt-2 flex flex-wrap items-center gap-3"><span className="flex items-center gap-2 rounded-full border border-[#d8e5de] bg-white/80 px-3 py-2 text-sm font-bold text-muted-foreground"><CalendarClock className="h-4 w-4"/>Due {formatDateTime(assignment.dueDate)}</span>{existing?<Badge variant={existing.grade!=null?"success":"warning"}>{existing.grade!=null?`Graded: ${existing.grade}%`:"Submitted"}</Badge>:<Badge variant="danger">Pending</Badge>}</div></div><Card className="mt-6"><CardHeader><CardTitle>Assignment instructions</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap leading-7 text-muted-foreground">{assignment.description}</p></CardContent></Card><Card className="mt-6"><CardHeader><CardTitle>Your submission</CardTitle></CardHeader><CardContent><SubmissionForm assignmentId={assignment.id} existing={existing}/>{existing?.feedback?<div className="premium-card-subtle mt-6 p-4"><p className="font-black text-emerald-800">Lecturer feedback</p><p className="mt-2 text-sm leading-6 text-emerald-700">{existing.feedback}</p></div>:null}</CardContent></Card></div></DashboardShell>}
