import type { Metadata } from "next";
import { Mail, MessageCircle, ShieldCheck } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { ContactForm } from "@/components/forms/contact-form";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export const metadata: Metadata = { title: "Contact", description: "Contact the SecureLearn administrator and support team." };

export default async function ContactPage({ searchParams }: { searchParams: Promise<{ reason?: string; email?: string }> }) {
  const { reason, email } = await searchParams;
  const isAccountAppeal = reason === "disabled-account";
  return <><SiteHeader /><main><section className="route-hero"><div className="page-container route-hero-grid"><div className="route-copy"><p className="kicker">Contact</p><h1>{isAccountAppeal ? "Appeal a disabled account." : "Send a message to the SecureLearn team."}</h1><p>{isAccountAppeal ? "Explain the circumstances surrounding your disabled account. Your message will enter the administrator review queue." : "Use this form for account support, learning enquiries, or platform feedback. Messages are saved securely for administrator review."}</p><div className="auth-signal-list"><div className="flex gap-3"><Mail className="mt-1 h-5 w-5 text-primary" /><div><p className="font-black text-[#12201c]">Administrator contact</p><p className="text-sm leading-6 text-muted-foreground">admin@securelearn.test</p></div></div><div className="flex gap-3"><MessageCircle className="mt-1 h-5 w-5 text-primary" /><div><p className="font-black text-[#12201c]">Account appeals and support</p><p className="text-sm leading-6 text-muted-foreground">Each submission appears in the administrator inbox.</p></div></div></div></div><aside className="hero-terminal premium-card"><div className="terminal-row"><span>Destination</span><strong>Administrator inbox</strong></div><div className="terminal-row"><span>Visibility</span><strong>Restricted review</strong></div><div className="terminal-row"><span>Privacy</span><strong>Secure storage</strong></div><div className="absolute bottom-4 left-4 right-4 z-10 rounded-lg border border-white/15 bg-white/10 p-4 backdrop-blur-md"><ShieldCheck className="h-6 w-6 text-[#b7f0dc]" /><p className="mt-3 text-sm font-bold leading-6 text-white/75">Never send fingerprint data, passwords, or one-time codes through this form.</p></div></aside></div></section><section className="page-container py-10"><Card className="mx-auto max-w-3xl"><CardHeader><CardTitle>{isAccountAppeal ? "Account appeal" : "Contact form"}</CardTitle></CardHeader><CardContent><ContactForm initialEmail={email || ""} initialSubject={isAccountAppeal ? "Disabled account appeal" : ""} /></CardContent></Card></section></main><SiteFooter /></>;
}
