import { Fingerprint, KeyRound, ShieldCheck, Smartphone } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { PasskeyEnrolment } from "@/components/auth/passkey-enrolment";
import { TotpEnrolment } from "@/components/auth/totp-enrolment";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default async function PasskeySetupPage() {
  const user = await requireUser();
  return <DashboardShell user={user}><div className="mx-auto max-w-6xl space-y-6"><section className="premium-card bg-[#12201c] p-7 text-white"><p className="text-xs font-black uppercase text-[#b7f0dc]">Account security</p><h1 className="mt-3 text-4xl font-semibold leading-none" style={{ fontFamily: "var(--font-editorial), var(--font-sans), serif" }}>Passkeys and multi-factor authentication</h1><p className="mt-4 max-w-3xl text-sm leading-6 text-white/72">Use a device-backed passkey for phishing-resistant biometric sign-in, and optionally require a rotating authenticator code after password login.</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-white/12 bg-white/8 p-4"><ShieldCheck className="h-5 w-5 text-[#b7f0dc]" /><p className="mt-3 text-sm font-bold text-white/72">Local biometric prompt</p></div><div className="rounded-lg border border-white/12 bg-white/8 p-4"><KeyRound className="h-5 w-5 text-[#f5cb78]" /><p className="mt-3 text-sm font-bold text-white/72">Public key verification</p></div><div className="rounded-lg border border-white/12 bg-white/8 p-4"><Smartphone className="h-5 w-5 text-white" /><p className="mt-3 text-sm font-bold text-white/72">30-second TOTP codes</p></div></div></section><div className="grid gap-5 lg:grid-cols-2"><Card><CardHeader><div className="mb-3 grid h-11 w-11 place-items-center rounded-lg bg-primary/10 text-primary"><Fingerprint className="h-5 w-5" /></div><CardTitle>Enrol a trusted device</CardTitle><CardDescription>The exact device prompt depends on your operating system and browser.</CardDescription></CardHeader><CardContent><PasskeyEnrolment existingCount={user.webAuthnCredentials.length} /></CardContent></Card><Card><CardHeader><div className="mb-3 grid h-11 w-11 place-items-center rounded-lg bg-primary/10 text-primary"><Smartphone className="h-5 w-5" /></div><CardTitle>Authenticator app</CardTitle><CardDescription>Add a separate verification step to password sign-ins.</CardDescription></CardHeader><CardContent><TotpEnrolment enabled={user.totpEnabled}/></CardContent></Card></div></div></DashboardShell>;
}
