import type { Metadata } from "next";
import { Fingerprint, KeyRound, LockKeyhole, Radar, Server, ShieldCheck } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { Card, CardContent } from "@/components/ui/card";

export const metadata: Metadata = { title: "About", description: "About SecureLearn and its privacy-first passkey security model." };

export default function AboutPage() {
  const steps = [
    { icon: Fingerprint, title: "Local verification", text: "The user's fingerprint or device screen lock is checked by the phone or computer, not by this web application." },
    { icon: KeyRound, title: "Cryptographic proof", text: "The authenticator signs a one-time challenge using a private key that remains protected on the device." },
    { icon: Server, title: "Public credential storage", text: "The database stores the credential ID, public key, signature counter and non-biometric metadata." },
    { icon: LockKeyhole, title: "Secure access", text: "The server verifies the signature, creates an HTTP-only session and applies role-based authorisation." }
  ];
  return <><SiteHeader /><main><section className="route-hero"><div className="page-container route-hero-grid"><div className="route-copy"><p className="kicker">About SecureLearn</p><h1>A privacy-first learning platform with biometric-backed trust.</h1><p>SecureLearn protects collaborative and personalised e-learning with modern passkey authentication without collecting or storing fingerprints.</p><div className="route-actions"><span className="rounded-full border border-[#d8e5de] bg-white/80 px-3 py-2 text-sm font-black text-[#12201c]"><ShieldCheck className="mr-2 inline h-4 w-4 text-primary"/>No raw prints</span><span className="rounded-full border border-[#d8e5de] bg-white/80 px-3 py-2 text-sm font-black text-[#12201c]"><Radar className="mr-2 inline h-4 w-4 text-primary"/>Auditable access</span></div></div><aside className="hero-terminal premium-card"><div className="terminal-row"><span>Fingerprint scan</span><strong>Device-side</strong></div><div className="terminal-row"><span>Server proof</span><strong>Signed challenge</strong></div><div className="terminal-row"><span>Storage model</span><strong>Public credentials</strong></div></aside></div></section><section className="section-padding bg-white/74"><div className="page-container"><div className="grid gap-8 lg:grid-cols-2"><div className="page-heading"><h1>Learning with privacy</h1><p>SecureLearn supports student learning, lecturer course administration, collaboration, assignment workflows, personalised recommendations, and administrative oversight. Its security model treats fingerprint authentication responsibly for the web.</p><p>Instead of building an unsafe fingerprint database, the system uses WebAuthn. Modern devices can satisfy the biometric prompt through built-in authenticators such as Windows Hello, Android screen lock, or Apple Touch ID.</p></div><Card className="bg-[#12201c] text-white"><CardContent className="p-8"><Fingerprint className="h-12 w-12 text-emerald-300" /><h2 className="mt-6 text-2xl font-black">What the database never stores</h2><ul className="mt-5 space-y-3 text-sm leading-6 text-white/72"><li>Raw fingerprint images</li><li>Fingerprint templates</li><li>Biometric matching scores</li><li>Device PINs or screen-lock secrets</li></ul></CardContent></Card></div><div className="mt-12 grid gap-5 md:grid-cols-2">{steps.map(({ icon: Icon, title, text }, index) => <Card key={title} className="hover:-translate-y-0.5 hover:border-primary/25"><CardContent className="p-6"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><span className="text-sm font-black text-muted-foreground">0{index + 1}</span></div><h3 className="mt-5 text-lg font-black text-[#12201c]">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></CardContent></Card>)}</div></div></section></main><SiteFooter /></>;
}
