import type { Metadata } from "next";
import { Fingerprint, KeyRound, LockKeyhole, Server } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { SiteFooter } from "@/components/layout/site-footer";
import { Card, CardContent } from "@/components/ui/card";

export const metadata: Metadata = { title: "About", description: "About the SecureLearn final year academic project and its privacy-first passkey security model." };

export default function AboutPage() {
  const steps = [
    { icon: Fingerprint, title: "Local verification", text: "The user's fingerprint or device screen lock is checked by the phone or computer, not by this web application." },
    { icon: KeyRound, title: "Cryptographic proof", text: "The authenticator signs a one-time challenge using a private key that remains protected on the device." },
    { icon: Server, title: "Public credential storage", text: "The database stores the credential ID, public key, signature counter and non-biometric metadata." },
    { icon: LockKeyhole, title: "Secure access", text: "The server verifies the signature, creates an HTTP-only session and applies role-based authorisation." }
  ];
  return <><SiteHeader /><main><section className="gradient-hero section-padding"><div className="page-container max-w-4xl text-center"><p className="font-semibold text-primary">Final year Computer Science project</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">About SecureLearn</h1><p className="mx-auto mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">This project demonstrates how collaborative and personalised e-learning can be protected with modern biometric-backed authentication without collecting or storing fingerprints.</p></div></section><section className="section-padding bg-white"><div className="page-container"><div className="grid gap-8 lg:grid-cols-2"><div><h2 className="text-3xl font-bold">Academic purpose</h2><p className="mt-4 leading-7 text-muted-foreground">SecureLearn is a working prototype designed to support student learning, lecturer course administration, collaboration, assignment workflows, personalised recommendations and administrative oversight. Its key research contribution is the responsible interpretation of fingerprint authentication for the web.</p><p className="mt-4 leading-7 text-muted-foreground">Instead of building an unsafe fingerprint database, the system uses the Web Authentication API. This approach is realistic for deployment because modern devices can use built-in authenticators such as Windows Hello, Android screen lock or Apple Touch ID.</p></div><Card className="bg-slate-950 text-white"><CardContent className="p-8"><Fingerprint className="h-12 w-12 text-emerald-400" /><h2 className="mt-6 text-2xl font-bold">What the database never stores</h2><ul className="mt-5 space-y-3 text-slate-300"><li>• Raw fingerprint images</li><li>• Fingerprint templates</li><li>• Biometric matching scores</li><li>• Device PINs or screen-lock secrets</li></ul></CardContent></Card></div><div className="mt-12 grid gap-5 md:grid-cols-2">{steps.map(({ icon: Icon, title, text }, index) => <Card key={title}><CardContent className="p-6"><div className="flex items-center gap-4"><span className="grid h-11 w-11 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><span className="text-sm font-bold text-muted-foreground">0{index + 1}</span></div><h3 className="mt-5 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></CardContent></Card>)}</div></div></section></main><SiteFooter /></>;
}
