import { NextResponse } from "next/server";
import { z } from "zod";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { logSecurityEvent } from "@/lib/security-log";
import { apiError } from "@/lib/api";
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const admin=await getCurrentUser();if(!admin||admin.role!=="ADMIN")return NextResponse.json({error:"Admin access required."},{status:403});const{id}=await params;try{if(id===admin.id)throw new Error("You cannot disable your own administrator account.");const{isActive}=z.object({isActive:z.boolean()}).parse(await request.json());const user=await db.user.update({where:{id},data:{isActive},select:{id:true,name:true,email:true,role:true,isActive:true}});if(!isActive)await db.session.deleteMany({where:{userId:id}});await logSecurityEvent({request,userId:admin.id,action:"ADMIN_USER_STATUS",status:"SUCCESS",metadata:{targetUserId:id,isActive}});return NextResponse.json({user});}catch(error){return apiError(error,"Admin action failed");}}

export async function DELETE(request:Request,{params}:{params:Promise<{id:string}>}){const admin=await getCurrentUser();if(!admin||admin.role!=="ADMIN")return NextResponse.json({error:"Admin access required."},{status:403});const{id}=await params;if(id===admin.id)return NextResponse.json({error:"You cannot delete your own administrator account."},{status:400});try{const target=await db.user.findUnique({where:{id},select:{id:true,name:true,email:true,role:true,_count:{select:{courses:true,enrollments:true,submissions:true}}}});if(!target)return NextResponse.json({error:"User not found."},{status:404});if(target.role==="ADMIN")return NextResponse.json({error:"Administrator accounts cannot be permanently deleted from this page."},{status:400});await db.user.delete({where:{id}});await logSecurityEvent({request,userId:admin.id,action:"ADMIN_USER_DELETED",status:"SUCCESS",metadata:{targetUserId:target.id,targetName:target.name,targetEmail:target.email,targetRole:target.role,relatedRecords:target._count,permanent:true}});return NextResponse.json({success:true,deletedUser:{id:target.id,name:target.name,role:target.role}});}catch(error){return apiError(error,"User could not be deleted");}}
