import Link from "next/link";
import { BookOpen, FileClock, Plus, Users } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { StatCard } from "@/components/dashboard/stat-card";
import { EngagementChart } from "@/components/dashboard/engagement-chart";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { buttonVariants } from "@/components/ui/button";

export default async function LecturerDashboard(){const user=await requireUser(["LECTURER"]);const courses=await db.course.findMany({where:{lecturerId:user.id},include:{_count:{select:{enrollments:true,assignments:true}},assignments:{include:{_count:{select:{submissions:true}}}}},orderBy:{createdAt:"desc"}});const totalStudents=courses.reduce((sum,c)=>sum+c._count.enrollments,0);const totalSubmissions=courses.reduce((sum,c)=>sum+c.assignments.reduce((s,a)=>s+a._count.submissions,0),0);const pending=await db.submission.count({where:{assignment:{course:{lecturerId:user.id}},grade:null}});const chartData=courses.slice(0,6).map(c=>({name:c.title.length>15?`${c.title.slice(0,15)}...`:c.title,students:c._count.enrollments,submissions:c.assignments.reduce((s,a)=>s+a._count.submissions,0)}));return <DashboardShell user={user}><div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="page-heading"><h1>Lecturer dashboard</h1><p>Manage teaching content, assignments and student engagement.</p></div><Link href="/lecturer/courses/new" className={buttonVariants()}><Plus className="h-4 w-4"/>Create course</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Total courses" value={courses.length} icon={BookOpen}/><StatCard label="Total enrolments" value={totalStudents} icon={Users}/><StatCard label="Submissions received" value={totalSubmissions} icon={FileClock}/><StatCard label="Pending reviews" value={pending} icon={FileClock}/></div><div className="grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle>Engagement overview</CardTitle></CardHeader><CardContent>{chartData.length?<EngagementChart data={chartData}/>:<p className="py-20 text-center text-sm text-muted-foreground">Create courses to see engagement analytics.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Recent courses</CardTitle></CardHeader><CardContent className="space-y-4">{courses.slice(0,5).map(c=><div key={c.id} className="record-item flex items-center justify-between gap-3 p-3"><div><p className="font-black text-[#12201c]">{c.title}</p><p className="mt-1 text-xs text-muted-foreground">{c._count.enrollments} students · {c._count.assignments} assignments</p></div><Badge variant={c.isPublished?"success":"warning"}>{c.isPublished?"Published":"Draft"}</Badge></div>)}{!courses.length?<p className="text-sm text-muted-foreground">No courses created yet.</p>:null}<Link href="/lecturer/courses" className={buttonVariants({variant:"outline",className:"w-full"})}>Manage all courses</Link></CardContent></Card></div></div></DashboardShell>}
