import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatDate } from "@/lib/utils";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { AdminUserAction } from "@/components/forms/admin-user-action";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";

export default async function AdminUsersPage({searchParams}:{searchParams:Promise<{role?:string}>}){const admin=await requireUser(["ADMIN"]);const{role}=await searchParams;const users=await db.user.findMany({where:role&&["STUDENT","LECTURER","ADMIN"].includes(role)?{role:role as "STUDENT"|"LECTURER"|"ADMIN"}:{},select:{id:true,name:true,email:true,role:true,isActive:true,createdAt:true,_count:{select:{webAuthnCredentials:true,enrollments:true,courses:true}}},orderBy:{createdAt:"desc"}});return <DashboardShell user={admin}><div className="space-y-6"><div className="page-heading"><h1>User management</h1><p>Review account activity, enable or disable access, and permanently remove student or lecturer records when required.</p></div><form className="data-toolbar"><select name="role" defaultValue={role||""} className="select-control"><option value="">All roles</option><option value="STUDENT">Students</option><option value="LECTURER">Lecturers</option><option value="ADMIN">Admins</option></select><button className={buttonVariants()}>Filter</button></form><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="data-table min-w-[980px]"><thead><tr><th>User</th><th>Role</th><th>Passkeys</th><th>Activity</th><th>Joined</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><p className="font-black text-[#12201c]">{user.name}</p><p className="text-xs text-muted-foreground">{user.email}</p></td><td><Badge>{user.role}</Badge></td><td className="font-black text-[#12201c]">{user._count.webAuthnCredentials}</td><td className="text-xs text-muted-foreground">{user.role==="STUDENT"?`${user._count.enrollments} enrolments`:user.role==="LECTURER"?`${user._count.courses} courses`:"Administration"}</td><td>{formatDate(user.createdAt)}</td><td><Badge variant={user.isActive?"success":"danger"}>{user.isActive?"Active":"Disabled"}</Badge></td><td>{user.id!==admin.id?<AdminUserAction userId={user.id} userName={user.name} userRole={user.role} isActive={user.isActive}/>:<span className="text-xs text-muted-foreground">Current admin</span>}</td></tr>)}</tbody></table></div></CardContent></Card></div></DashboardShell>}
