import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatDate } from "@/lib/utils";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { AdminUserAction } from "@/components/forms/admin-user-action";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

export default async function AdminUsersPage({searchParams}:{searchParams:Promise<{role?:string}>}){const admin=await requireUser(["ADMIN"]);const{role}=await searchParams;const users=await db.user.findMany({where:role&&["STUDENT","LECTURER","ADMIN"].includes(role)?{role:role as "STUDENT"|"LECTURER"|"ADMIN"}:{},include:{_count:{select:{webAuthnCredentials:true,enrollments:true,courses:true}}},orderBy:{createdAt:"desc"}});return <DashboardShell user={admin}><div className="space-y-6"><div><h1 className="text-3xl font-bold">User management</h1><p className="mt-2 text-muted-foreground">Review roles, passkey adoption and account status.</p></div><form className="flex gap-3"><select name="role" defaultValue={role||""} className="h-10 rounded-md border bg-white px-3 text-sm"><option value="">All roles</option><option value="STUDENT">Students</option><option value="LECTURER">Lecturers</option><option value="ADMIN">Admins</option></select><button className="rounded-md bg-primary px-4 text-sm font-semibold text-white">Filter</button></form><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">User</th><th>Role</th><th>Passkeys</th><th>Activity</th><th>Joined</th><th>Status</th><th className="pr-4">Action</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className="border-t"><td className="p-4"><p className="font-medium">{user.name}</p><p className="text-xs text-muted-foreground">{user.email}</p></td><td><Badge>{user.role}</Badge></td><td>{user._count.webAuthnCredentials}</td><td className="text-xs text-muted-foreground">{user.role==="STUDENT"?`${user._count.enrollments} enrolments`:user.role==="LECTURER"?`${user._count.courses} courses`:"Administration"}</td><td>{formatDate(user.createdAt)}</td><td><Badge variant={user.isActive?"success":"danger"}>{user.isActive?"Active":"Disabled"}</Badge></td><td className="pr-4">{user.id!==admin.id?<AdminUserAction userId={user.id} isActive={user.isActive}/>:<span className="text-xs text-muted-foreground">Current admin</span>}</td></tr>)}</tbody></table></div></CardContent></Card></div></DashboardShell>}
