import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatDateTime } from "@/lib/utils";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { buttonVariants } from "@/components/ui/button";

export default async function SecurityLogsPage({searchParams}:{searchParams:Promise<{status?:string;action?:string}>}){const admin=await requireUser(["ADMIN"]);const{status,action}=await searchParams;const logs=await db.securityLog.findMany({where:{...(status&&["SUCCESS","FAILURE","WARNING"].includes(status)?{status:status as "SUCCESS"|"FAILURE"|"WARNING"}:{}),...(action?{action:{contains:action,mode:"insensitive"}}:{})},include:{user:{select:{name:true,email:true,role:true}}},orderBy:{createdAt:"desc"},take:250});return <DashboardShell user={admin}><div className="space-y-6"><div className="page-heading"><h1>Security logs</h1><p>Audit authentication, passkey enrolment, submissions, course actions and administrator activity.</p></div><form className="data-toolbar"><input name="action" defaultValue={action||""} placeholder="Filter action" className="select-control"/><select name="status" defaultValue={status||""} className="select-control"><option value="">All statuses</option><option>SUCCESS</option><option>FAILURE</option><option>WARNING</option></select><button className={buttonVariants()}>Filter</button></form><Card><CardContent className="p-0"><div className="overflow-x-auto"><table className="data-table min-w-[1000px]"><thead><tr><th>Date/time</th><th>Action</th><th>User</th><th>Role</th><th>Status</th><th>IP address</th><th>User agent</th></tr></thead><tbody>{logs.map(log=><tr key={log.id}><td className="text-xs text-muted-foreground">{formatDateTime(log.createdAt)}</td><td className="font-black text-[#12201c]">{log.action}</td><td>{log.user?<><p>{log.user.name}</p><p className="text-xs text-muted-foreground">{log.user.email}</p></>:"Guest/System"}</td><td>{log.user?.role||"-"}</td><td><Badge variant={log.status==="SUCCESS"?"success":log.status==="FAILURE"?"danger":"warning"}>{log.status}</Badge></td><td>{log.ipAddress}</td><td className="max-w-xs truncate text-xs text-muted-foreground" title={log.userAgent||""}>{log.userAgent}</td></tr>)}</tbody></table></div></CardContent></Card></div></DashboardShell>}
