import { FileText } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { formatDateTime } from "@/lib/utils";
import { DashboardShell } from "@/components/layout/dashboard-shell";
import { ReviewForm } from "@/components/forms/review-form";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

export default async function LecturerSubmissionsPage(){const user=await requireUser(["LECTURER"]);const submissions=await db.submission.findMany({where:{assignment:{course:{lecturerId:user.id}}},include:{student:{select:{name:true,email:true}},assignment:{include:{course:{select:{title:true}}}}},orderBy:{submittedAt:"desc"}});return <DashboardShell user={user}><div className="space-y-6"><div className="page-heading"><h1>Student submissions</h1><p>Review student work, add a grade and provide feedback.</p></div>{submissions.length?<div className="space-y-5">{submissions.map(s=><Card key={s.id}><CardContent className="grid gap-6 p-6 lg:grid-cols-[1.2fr_0.8fr]"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-black text-[#12201c]">{s.assignment.title}</h2><Badge variant={s.grade==null?"warning":"success"}>{s.grade==null?"Pending review":`${s.grade}%`}</Badge>{s.isLate?<Badge variant="danger">Late</Badge>:null}</div><p className="mt-1 text-sm text-muted-foreground">{s.assignment.course.title} - {s.student.name} ({s.student.email})</p><p className="mt-1 text-xs text-muted-foreground">Submitted {formatDateTime(s.submittedAt)}</p><div className="premium-card-subtle mt-4 p-4"><p className="whitespace-pre-wrap text-sm leading-6">{s.content}</p>{s.fileUrl?<a href={s.fileUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-sm font-black text-primary">Open submitted file link</a>:null}</div></div><ReviewForm submissionId={s.id} grade={s.grade} feedback={s.feedback}/></CardContent></Card>)}</div>:<div className="empty-premium"><div><span className="mx-auto grid h-14 w-14 place-items-center rounded-lg bg-[#eef8f1] text-primary"><FileText className="h-7 w-7"/></span><h2 className="mt-4 font-black text-[#12201c]">No submissions yet</h2><p className="mt-2 text-sm text-muted-foreground">Student submissions for your courses will appear here.</p></div></div>}</div></DashboardShell>}
