"use client";
import Image from "next/image";
import { useState } from "react";
import { Camera, Trash2 } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { SubmitButton } from "@/components/ui/submit-button";
import { Alert } from "@/components/ui/alert";
import { Toast } from "@/components/ui/toast";

export function ProfileForm({ name, email, avatarDataUrl: initialAvatar }: { name: string; email: string; avatarDataUrl?: string | null }) {
  const [loading,setLoading]=useState(false); const [message,setMessage]=useState<{type:"success"|"error";text:string}|null>(null);
  const [avatarDataUrl,setAvatarDataUrl]=useState<string|null>(initialAvatar||null);
  function choosePhoto(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setMessage({type:"error",text:"Choose a JPG, PNG or WebP image."});return;}if(file.size>750*1024){setMessage({type:"error",text:"Profile picture must be smaller than 750 KB."});return;}const reader=new FileReader();reader.onload=()=>{setAvatarDataUrl(String(reader.result));setMessage(null);};reader.onerror=()=>setMessage({type:"error",text:"The selected image could not be read."});reader.readAsDataURL(file);}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage(null);const formData=new FormData(event.currentTarget);const data={name:formData.get("name"),avatarDataUrl};const response=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json();setLoading(false);setMessage(response.ok?{type:"success",text:"Profile updated successfully."}:{type:"error",text:result.error||"Update failed"});}
  return <form onSubmit={submit} className="space-y-5">{message?.type==="success"?<Toast message={message.text} onClose={()=>setMessage(null)}/>:null}{message?.type==="error"?<Alert variant="error">{message.text}</Alert>:null}<div className="flex flex-col gap-4 rounded-lg border border-[#d8e5de] bg-[#f7fbf8] p-4 sm:flex-row sm:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-lg bg-white text-primary shadow-sm">{avatarDataUrl?<Image src={avatarDataUrl} alt="Profile picture preview" width={96} height={96} unoptimized className="h-full w-full object-cover"/>:<Camera className="h-9 w-9"/>}</div><div className="min-w-0 flex-1"><p className="font-black text-[#12201c]">Profile picture</p><p className="mt-1 text-xs leading-5 text-muted-foreground">JPG, PNG or WebP, up to 750 KB.</p><div className="mt-3 flex flex-wrap gap-2"><label htmlFor="avatar-upload" className="inline-flex min-h-9 cursor-pointer items-center justify-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-black text-white"><Camera className="h-4 w-4"/>{avatarDataUrl?"Replace photo":"Upload photo"}</label><input id="avatar-upload" type="file" accept="image/jpeg,image/png,image/webp" className="sr-only" onChange={choosePhoto}/>{avatarDataUrl?<button type="button" onClick={()=>setAvatarDataUrl(null)} className="inline-flex min-h-9 items-center justify-center gap-2 rounded-md border border-red-200 bg-white px-3 py-2 text-sm font-black text-red-700"><Trash2 className="h-4 w-4"/>Remove</button>:null}</div></div></div><div className="space-y-2"><Label htmlFor="name">Full name</Label><Input id="name" name="name" defaultValue={name} required /></div><div className="space-y-2"><Label>Email address</Label><Input value={email} disabled /><p className="text-xs text-muted-foreground">Email changes are disabled to protect credential ownership.</p></div><SubmitButton loading={loading}>Save profile</SubmitButton></form>;
}
